// Mock product data for development
export const mockProductsData = [
  {
    id: 1,
    name: 'Apple Mint (12mg)',
    flavor: 'Apple Mint',
    strength: 12,
    price: 6.99,
    image_url: '/images/products/apple-mint/apple-mint-12mg.png',
    category: 'Regular Strength',
    description: 'Crisp apple and cool mint flavor.',
    is_active: true,
  },
  {
    id: 2,
    name: 'Apple Mint (6mg)',
    flavor: 'Apple Mint',
    strength: 6,
    price: 6.99,
    image_url: '/images/products/apple-mint/apple-mint-6mg.png',
    category: 'Mild',
    description: 'Crisp apple and cool mint flavor, lower strength.',
    is_active: true,
  },
  {
    id: 3,
    name: 'Mint (12mg)',
    flavor: 'Mint',
    strength: 12,
    price: 6.99,
    image_url: '/images/products/cool-mint-6mg.png',
    category: 'Regular Strength',
    description: 'Cool and refreshing mint flavor.',
    is_active: true,
  },
  {
    id: 4,
    name: 'Mint (6mg)',
    flavor: 'Mint',
    strength: 6,
    price: 6.99,
    image_url: '/images/products/cool-mint-6mg.png',
    category: 'Mild',
    description: 'Cool and refreshing mint flavor, lower strength.',
    is_active: true,
  },
  {
    id: 5,
    name: 'PUXX Classic Mint',
    flavor: 'Mint',
    strength: 22,
    price: 15.0,
    image_url: '/images/products/puxxcoolmint22mg.png',
    category: 'Strong',
    description: 'Refined flavor profile with subtle cooling effect.',
    is_active: true,
  },
  {
    id: 6,
    name: 'PUXX Peppermint',
    flavor: 'Peppermint',
    strength: 22,
    price: 15.0,
    image_url: '/images/products/puxxperpermint22mg.png',
    category: 'Strong',
    description: 'Crisp peppermint with exceptional clarity.',
    is_active: true,
  },
  {
    id: 7,
    name: 'PUXX Spearmint',
    flavor: 'Spearmint',
    strength: 22,
    price: 15.0,
    image_url: '/images/products/puxxspearmint22mg.png',
    category: 'Strong',
    description: 'Sophisticated spearmint with lasting freshness.',
    is_active: true,
  },
  {
    id: 8,
    name: 'PUXX Watermelon',
    flavor: 'Watermelon',
    strength: 16,
    price: 15.0,
    image_url: '/images/products/puxxwatermelon16mg.png',
    category: 'Medium',
    description: 'Sweet and refreshing watermelon flavor.',
    is_active: true,
  },
  {
    id: 9,
    name: 'PUXX Cola',
    flavor: 'Cola',
    strength: 16,
    price: 15.0,
    image_url: '/images/products/puxxcola16mg.png',
    category: 'Medium',
    description: 'Classic cola flavor with a refreshing twist.',
    is_active: true,
  },
];
